/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio_05;

import java.security.MessageDigest;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author ESTUDIANTE
 */
public class JFrame_Estudiantes extends javax.swing.JFrame {

    DefaultListModel modelo = new DefaultListModel();
    List<Estudiante> listaEstudiantes = new ArrayList<>();
    
    
    public JFrame_Estudiantes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JFLista = new javax.swing.JList<>();
        lblBuscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtBuscar = new javax.swing.JTextField();
        lblnull = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE ESTUDIANTES");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(201, 222, 255));

        JFLista.setBorder(null);
        JFLista.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        JFLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JFLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JFLista);

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnBuscar.png"))); // NOI18N
        lblBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBuscarMouseDragged(evt);
            }
        });
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBuscarMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ESTUDIANTES");

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtBuscar.setBorder(null);
        jLayeredPane1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 300, 30));

        lblnull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Rectangle 3.png"))); // NOI18N
        jLayeredPane1.add(lblnull, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, -1));

        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnAgregar.png"))); // NOI18N
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnEditar.png"))); // NOI18N
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnEliminar.png"))); // NOI18N
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditar)
                        .addGap(103, 103, 103)
                        .addComponent(lblEliminar)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregar)
                    .addComponent(lblEditar)
                    .addComponent(lblEliminar))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseClicked
        // TODO add your handling code here:
        //Aqui escribimos lo que pasara si cliekeamos
        //Primero cambiamos la imagen
        lblBuscar.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/IMG/btnBuscar.png")));
        
        //Ahora sacamos el texto del txtBuscar
        String stud_buscado = txtBuscar.getText();
        //Evaluamos si esta vacio
        if(stud_buscado.equals("")){
            //No hacemso nada
        }else{
            //Ahora buscamos en la lista
            //iteramos en cada posicion
            int pos=-1;
            for(int i = 0 ; i<listaEstudiantes.size(); i++){
                //Ahora en cada elemento estudiante
                Estudiante estud_actual = listaEstudiantes.get(i);
                //Vemos si se encuentra el stud_buscado
                if( estud_actual.getNombre().equals(stud_buscado)||
                    estud_actual.getApellido().equals(stud_buscado)||
                    estud_actual.getCodigo().equals(stud_buscado)){
                    pos = i;
                    break;
                }
            }
            //Mostramos el mensaje
            if(pos != -1){
                
                JOptionPane.showMessageDialog(null,""
                    + "El Dato fue encontrado en la fila "+ (pos+1));
            }
            else{
                JOptionPane.showMessageDialog(null,""
                    + "El Dato NO fue encontrado");
            }
            
            
        }
        
        
    }//GEN-LAST:event_lblBuscarMouseClicked

    private void lblBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMousePressed
        // TODO add your handling code here:
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnBuscar_P.png")));
    }//GEN-LAST:event_lblBuscarMousePressed

    private void lblBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseExited
        // TODO add your handling code here:
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnBuscar.png")));
    }//GEN-LAST:event_lblBuscarMouseExited

    private void lblBuscarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMouseDragged
        // TODO add your handling code here:
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/btnBuscar.png")));
    }//GEN-LAST:event_lblBuscarMouseDragged

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        // TODO add your handling code here:
        //AGREGAMOS UNA PERSONA A LA LISTA
        AbrirFrameEstudiante(0);
        
        
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        // TODO add your handling code here:
        //Buscamos al item selecionado
        if(JFLista.getSelectedIndex()==-1){
            //No hacemos nada
        }else {
            
            AbrirFrameEstudiante(1);
            
        }
    }//GEN-LAST:event_lblEditarMouseClicked

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        // TODO add your handling code here:
        //Buscamos el indice actual
        int index = BuscarIndiceActual();
        if(index == -1){
            //No hacemos nada
        }else{
            //Lo removemos del modelo
            modelo.remove(index);
            //Lo removemos de la lista
            listaEstudiantes.remove(index);
            //Ahora actualizamos el modelo de la interfaz
            ActualizarModelo(modelo);
    
        }
    }//GEN-LAST:event_lblEliminarMouseClicked
    
    public void AbrirFrameEstudiante(int opcion){
        //Creamos un objeto de ventana2 y lo abrimos con Esta clase
        JFrame_Estudiante vent_estudiante = new JFrame_Estudiante(
        this,opcion);
        
        //Mostramos la ventana centrada
        vent_estudiante.setVisible(true);
        vent_estudiante.setLocationRelativeTo(null);
        this.setVisible(false);
    }
    
    public int BuscarIndiceActual(){
        int index = JFLista.getSelectedIndex();
        return index;
    }
    
    //Esta funcion solo se hace con la ventana agregar que lo manda aqui
    //Para que maneje las variable
    public void ActualizarModelo(DefaultListModel modelo){
        JFLista.setModel(modelo);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JFLista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblnull;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
